#! /usr/bin/env python
# coding=UTF-8
""" Index fields from SGA TEI to a SOLR instance"""

import os, sys
import solr
from lxml import etree as ET

if len(sys.argv) != 2:
    print 'Usage: ./sitemap-indexer.py path'
    sys.exit(1)

# Connect to solr instance
s = solr.SolrConnection('http://localhost:8080/solr')

# Populate fields for each XML file - each one is a "doc"
xml_dir = os.path.normpath(sys.argv[1]) + os.sep

for f in os.listdir(xml_dir):
    if f.endswith('.xml'):
        tree = ET.parse(xml_dir + f)
        root = tree.getroot()

        # get field values
        tei_id = root.attrib["{http://www.w3.org/XML/1998/namespace}id"]
        shelfmark =  root.attrib["partOf"][1:] if root.attrib["partOf"][0] == "#" else root.attrib["partOf"]
        # separate text into different hands (a general text field for cross searched is generated by solr)
        text_pbs = []
        text_ms = []
        elements = root.findall(".//*")
        for e in elements:
            if len(e.xpath("ancestor::*[@hand][1][@hand='#pbs']")) > 0:
            	if e.text != None: #skips empty elements
            	    if e.text.strip() != '': #skips "white" elements
            	        text_pbs.append(e.text.strip())
    	    elif e.text != None:
    	    	if e.text.strip() != '':
    	    		text_ms.append(e.text.strip())

		# add current document to the index
		s.add(id=tei_id, shelfmark=shelfmark, text_pbs=text_pbs, text_ms=text_ms)
		s.commit()

