// Generated by CoffeeScript 1.4.0
(function() {

  (function($) {
    var solrSearch;
    AjaxSolr.ResultWidget = AjaxSolr.AbstractWidget.extend({
      facets: [["hand_mws", "Mary Shelley's hand"], ["hand_pbs", "Percy Shelley's hand"], ["added", "added text"], ["deleted", "deleted text"]],
      beforeRequest: function() {
        return $(this.target).html($('<img/>').attr('src', 'images/ajax-loader.gif'));
      },
      afterRequest: function() {
        var doc, f, facets, response, self, t, _i, _j, _len, _len1, _ref, _ref1, _results;
        self = this;
        $(this.target).empty();
        response = this.manager.response;
        facets = $('#facets').html("<ul/>");
        _ref = self.facets;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          f = _ref[_i];
          facets.append(self.facetLinks(f[1], self.facetHandler(self, f[0], self.q)));
        }
        t = $(this.target).append("<dl/>");
        if (response.response.docs.length > 0) {
          t.append($("<strong/>").text("Found " + response.response.docs.length + " results"));
          _ref1 = response.response.docs;
          _results = [];
          for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
            doc = _ref1[_j];
            _results.push(t.append("<dt>" + doc.id + "</dt><dd>" + response.highlighting[doc.id].text + "</dd>"));
          }
          return _results;
        } else {
          return t.append("<dt>No results</dt><dd> </dd>");
        }
      },
      facetLinks: function(value, handler) {
        var self;
        self = this;
        return $('<li/>').append($('<a href="#"/>').text(value).click(handler));
      },
      facetHandler: function(that, facet_field, facet_value) {
        return function() {
          that.manager.store.remove('fq');
          that.manager.store.addByValue('fq', facet_field + ':' + AjaxSolr.Parameter.escapeValue(facet_value));
          that.doRequest();
          return false;
        };
      }
    });
    solrSearch = function(solr, term) {
      var Manager;
      Manager = new AjaxSolr.Manager({
        solrUrl: solr
      });
      Manager.init();
      Manager.store.addByValue('q', 'text:' + term);
      Manager.store.addByValue('rows', '999');
      Manager.store.addByValue('fl', 'id, text');
      Manager.store.addByValue('hl', 'true');
      Manager.store.addByValue('hl.fl', 'text');
      Manager.store.addByValue('sort', 'id asc');
      Manager.doRequest();
      return Manager.addWidget(new AjaxSolr.ResultWidget({
        id: 'result',
        q: term,
        target: '#docs'
      }));
    };
    return window.solrSearch = solrSearch;
  })(jQuery);

}).call(this);
